                                               בסייד

Задание 1

In [20]:
import numpy as np

def do_array(n):
 return np.arange(n-1, -1, -1)

do_array(10)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2

In [21]:
def do_matrix(n):
  matrix = np.diagflat(do_array(n))
  print(matrix)
  return f'Cумма значений на диагонали матрицы :{sum(np.diag(matrix))}'

do_matrix(3)  

[[2 0 0]
 [0 1 0]
 [0 0 0]]


'Cумма значений на диагонали матрицы :3'

Задание 3

In [4]:
# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3

from numpy import linalg

a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = [4, 12, -3]
linalg.solve(a, b)


array([ 0.46666667,  3.84444444, -5.55555556])

Задание 4 

In [19]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

result_cosin_list=[]

for user in users_stats:
  result_cosin_list.append(cosine(user, next_user_stats))
like_user_id = result_cosin_list.index(max(result_cosin_list))+1

print(f'Самый похожий пользователь- User ID :{like_user_id}')

Самый похожий пользователь- User ID :8
